# Generated by Django 4.2.3 on 2023-07-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_crud", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
