# Generated by Django 4.2.3 on 2023-07-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_crud", "0004_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
