# Generated by Django 4.2.3 on 2023-07-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_crud", "0005_alter_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(to="book_crud.author"),
        ),
    ]
