# Generated by Django 4.2.3 on 2023-08-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_crud", "0006_author_remove_book_author_book_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.IntegerField(),
        ),
    ]
