# Generated by Django 4.2.3 on 2023-08-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_crud', '0008_alter_book_image_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(null=True, to='book_crud.author'),
        ),
    ]
